version: '3.8'
name: shw-v8
services:

#Auth Service
  bachelor.auth:
    container_name: bachelor-auth
    image: bachelor.auth
    build:
      context: ../projects/microservices/BachelorAuth
      dockerfile: src/Auth.Web/Dockerfile
    ports:
      - "8083:80"
    networks:
      - "bachelor-backend"


  # MSSQL Database
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: thisIsSuperStrong1234
      SA_PASSWORD: thisIsSuperStrong1234
    ports:
      - "1433:1433"
    volumes:
      - data:/var/opt/mssql
    networks:
      - bachelor-backend
    
# Configuration
networks:
  bachelor-backend:
    name: bachelor-backend

volumes:
 data: