version: '3.8'
name: shw-v8
services:

# Kakfa and Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - bachelor-backend


  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - bachelor-backend

# Gateway
  bachelor.gateway:
    container_name: bachelor-gateway
    image: bachelor.gateway
    build:
      context: ../projects/microservices/BachelorGateway
      dockerfile: OcelotApiGateway/Dockerfile
    ports:
      - "8080:80"
    networks:
      - bachelor-backend
      - bachelor-frontend

#Chemicals Service
  bachelor.chemicals:
    container_name: bachelor-chemicals
    image: bachelor.chemicals
    build:
      context: ../projects/microservices/BachelorChemicals
      dockerfile: src/Chemicals.Web/Dockerfile
    ports:
      - "8081:80"
    networks:
      - "bachelor-backend"

#Warning Sentences Service
  bachelor.ws:
    container_name: bachelor-ws
    image: bachelor.ws
    build:
      context: ../projects/microservices/BachelorWS
      dockerfile: src/WS.Web/Dockerfile
    ports:
      - "8082:80"
    networks:
      - "bachelor-backend"

#Auth Service
  bachelor.auth:
    container_name: bachelor-auth
    image: bachelor.auth
    build:
      context: ../projects/microservices/BachelorAuth
      dockerfile: src/Auth.Web/Dockerfile
    ports:
      - "8083:80"
    networks:
      - "bachelor-backend"


  # MSSQL Database
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: thisIsSuperStrong1234
      SA_PASSWORD: thisIsSuperStrong1234
    ports:
      - "1433:1433"
    volumes:
      - data:/var/opt/mssql
    networks:
      - bachelor-backend
    
# Configuration
networks:
  bachelor-backend:
    name: bachelor-backend
  bachelor-frontend:
    name: bachelor-fronend

volumes:
 data: