server:
  http_listen_port: 9090
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

#docker logs
scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - labels:
        job: docker
        __path__: /var/lib/docker/containers/*/*-json.log
