name: CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.306"

      - name: Restore dependencies for WarningSentence tests
        run: dotnet restore ../../../bachelor/projects/microservices/BachelorWS/test/WS.Test

      - name: Run WarningSentence Tests
        run: dotnet test --configuration Release ../../../bachelor/projects/microservices/BachelorWS/test/WS.Test

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
