name: CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.306"

      - name: Navigate to users/frederik
        run: cd ../../..

      - name: Navigate to bachelor/projects/microservices/BachelorWS/test/WS.Test
        run: cd projects/microservices/BachelorWS/test/WS.Test

      - name: Restore dependencies for WarningSentences
        run: dotnet restore

      - name: Run WarningSentences tests
        run: dotnet test --configuration Release

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
